server: "hub-cloud.browserstack.com"
user: "aaronflynn1"
key: "8Wr7LhS1K5cqwqyaKnpV"

common_caps:
  "build": "capybara-browserstack"
  "browserstack.debug": true

browser_caps:
  -
    "browser": "chrome"
  -
    "browser": "firefox"
  -
    "browser": "internet explorer"
  -
    "browser": "safari"
